### ISSUE TITLE
Why is roswell required? 

### ISSUE THREAD

**Issue by defunkydrummer** [cxxxr/lsp-server#5]
Hi,

I see the install process requires roswell. However, by taking a look at [the ROS file](https://github.com/cxxxr/cl-lsp/blob/master/roswell/cl-lsp.ros), nothing of too much value is added by using Roswell -- just executing it as a command-line tool, as far as I see.

If that's the case, I'd strongly suggest to indicate that the project can simply be quickloaded like any other lib, and the server started by executing the appropriate function, and that Roswell is not mandatory for using cl-lsp. 

It specifies as mandatory what is really an unnecessary requirement.

**Comment by snmsts** [comment]
I know you come from the different culture. and you are true.
cl-lsp is not require roswell at all.But it is shorthand of documentation and what is your problem with this?
Do you do the same effort on the other language community like npm is not mandatory to install this library so you should write manual installation?

**Comment by snunez1** [comment]
The difference may not be entirely cultural here (or at least not a human culture). I was about to ask the same question. I notice that there are an increasing number of people using Roswell, and there are also a large number of CL hackers that do not and use Quicklisp. Perhaps this issue could be rephrased as "Add Quicklisp installation instructions" ?

**Comment by BracketMaster** [comment]
> project can simply be quickloaded like any other lib, and the server started by executing the appropriate function

I'm actually curious... How can I install cl-lsp without roswell?

**Comment by fstamour** [comment]
@cxxxr was this fixed? I was pretty much waiting on this issue to try this project

Roswell doesn't work on any of the systems I use

**Comment by snmsts** [comment]
@fstamour which system? I'm just curious.

**Comment by snmsts** [comment]
https://github.com/roswell/roswell/commit/1381da6ad84f8e932817a745b2aed95c65f8e7a3 It might be fixed if the system is guix/nix kind of distribution.

**Comment by fstamour** [comment]
GuixSD and NixOS are the main ones. But I also had issues when I tried roswell on FreeBSD.

Otherwise, I've had segfaults of all kind every time I've tried roswell. They might have been fixed since though.

**Comment by cxxxr** [comment]
Currently, it probably won't work without roswell.
Here is the technical description.

1. I want to isolate the runtime of the Language Server interface and the lisp process containing the user's data.
2. To do so, the language server must create an individual process.
3. In order to run-program a lisp process, you need some kind of launcher.
4. With roswell, you can eliminate the complexity of this launcher, just ros run.
   https://github.com/lem-project/lem/blob/8b02bc2d65db6963f5cdc260074c42cd13430a26/lib/language-server/micros-client.lisp#L232
5. Couldn't sbcl do this on its own?
   Yes, indeed it is. However, at present, it is not implemented and roswell is needed.

It is designed this way because I believe more roswell improvements to be made in the future.
